### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by luqasz** [corpnewt/USBMap#17]
Running from todays master
```python
Traceback (most recent call last):
  File "/tmp/USBMap/USBMap.py", line 1141, in <module>
    u.main()
  File "/tmp/USBMap/USBMap.py", line 1081, in main
    acpi = self.get_safe_acpi_path(self.connected_controllers[x].get("acpi_path","Unknown ACPI Path"))
  File "/tmp/USBMap/USBMap.py", line 898, in get_safe_acpi_path
    return ".".join([x.split("@")[0] for x in path.split("/") if len(x) and not ":" in x])
AttributeError: 'NoneType' object has no attribute 'split'
```
```
  #######################################################
 #                      USBMap                         #
#######################################################

Current Controllers:

 -         XHC@14 @ _SB.PCI0.XHC
  \-> RHUB @ _SB.PCI0.XHC.RHUB
 -   pci1033,35@0 @ _SB.PCI0.RP04.PXSX (Not Unique)
Traceback (most recent call last):
  File "/tmp/USBMap/USBMap.py", line 1141, in <module>
    u.main()
  File "/tmp/USBMap/USBMap.py", line 1081, in main
    acpi = self.get_safe_acpi_path(self.connected_controllers[x].get("acpi_path","Unknown ACPI Path"))
  File "/tmp/USBMap/USBMap.py", line 898, in get_safe_acpi_path
    return ".".join([x.split("@")[0] for x in path.split("/") if len(x) and not ":" in x])
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by trevjonez** [comment]
Similar issue for me. I do have two add in PCIE cards adding additional usb ports that are likely to blame?

```
Current Controllers:

 -         XHC@14 @ _SB.PCI0.XHC
  \-> RHUB @ _SB.PCI0.XHC.RHUB
 - pci1b21,2142@0 @ _SB.PCI0.RP17.PXSX (Not Unique)
  \-> RHUB @ _SB.PCI0.RP17.PXSX.APPLEUSBXHCIPCI
Traceback (most recent call last):
  File "/Volumes/Source/USBMap/USBMap.py", line 1144, in <module>
    u.main()
  File "/Volumes/Source/USBMap/USBMap.py", line 1084, in main
    acpi = self.get_safe_acpi_path(self.connected_controllers[x].get("acpi_path","Unknown ACPI Path"))
  File "/Volumes/Source/USBMap/USBMap.py", line 901, in get_safe_acpi_path
    return ".".join([x.split("@")[0] for x in path.split("/") if len(x) and not ":" in x])
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by JosephDuffy** [comment]
I ran in to this and fixed it by disabling my existing USBMap.kext that was created with an old version.

I also have 2 controllers: my onboard controller and a thunderbolt card.

**Comment by trevjonez** [comment]
I pulled my add in card out to do the mapping to build the kext, then also generated the RHUB aml. once I tested the kext map I added the pcie card back in and everything is working fine.

**Comment by luqasz** [comment]
I no longer have hackintosh. I am fed up with USB issues and overall lack of performance.
