### ISSUE TITLE
Program crashes with 3rd party USB PCIE

### ISSUE THREAD

**Issue by startergo** [corpnewt/USBMap#19]
```
Current Controllers:

 - pci1b21,2142@0 @ _SB.PCI0.IOU1.PXS2 (Not Unique)
  \-> RHUB @ _SB.PCI0.IOU1.PXS2.APPLEUSBXHCIPCI
Traceback (most recent call last):
  File "/Users/g5/Downloads/USBMap-master/USBMap.py", line 1147, in <module>
    u.main()
  File "/Users/g5/Downloads/USBMap-master/USBMap.py", line 1087, in main
    acpi = self.get_safe_acpi_path(self.connected_controllers[x].get("acpi_path","Unknown ACPI Path"))
  File "/Users/g5/Downloads/USBMap-master/USBMap.py", line 903, in get_safe_acpi_path
    return ".".join([x.split("@")[0] for x in path.split("/") if len(x) and not ":" in x])
AttributeError: 'NoneType' object has no attribute 'split'

```
Maybe adding something like:
```
902 def get_safe_acpi_path(self, path):
903 if get_safe_acpi_path is not None:
904 return ".".join([x.split("@")[0] for x in path.split("/") if len(x) and not ":" in x])
```

**Comment by startergo** [comment]
After adding:

```
def get_safe_acpi_path(self, path):
        if get_safe_acpi_path is not None:
        return ".".join([x.split("@")[0] for x in path.split("/") if len(x) and not ":" in x])
```
I get:

```
File "/Users/g5/.vscode/extensions/ms-python.python-2020.9.114305/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/Users/g5/.vscode/extensions/ms-python.python-2020.9.114305/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/Users/g5/.vscode/extensions/ms-python.python-2020.9.114305/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 267, in run_file
    runpy.run_path(options.target, run_name=compat.force_str("__main__"))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 251, in run_path
    code = _get_code_from_file(path_name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 232, in _get_code_from_file
    code = compile(f.read(), fname, 'exec')
  File "/Users/g5/Downloads/USBMap-master/USBMap.py", line 904
    return ".".join([x.split("@")[0] for x in path.split("/") if len(x) and not ":" in x])
         ^
IndentationError: expected an indented block

```
Not sure about this indentation error. It is not obvious to me.

**Comment by startergo** [comment]
Actually I made it work. Please change:
```
    def get_safe_acpi_path(self, path):
           if path is not None:
    		return ".".join([x.split("@")[0] for x in path.split("/") if len(x) and not ":" in x])

```
and

```
rhub_name = "RHUB" if x.split("@")[0].upper() == self.connected_controllers[x]["parent_name"] else x.split("@")[0].upper()
if acpi is not None:                
    rhub_path = ".".join([acpi,rhub_name])  

```
