### ISSUE TITLE
Where shall I need rename the current controllers QUO AOS mobo

### ISSUE THREAD

**Issue by lionB777** [corpnewt/USBMap#49]
Hello, I'm seeking for help
I'm unsure of where to rename the XHC1 because of the mobo I'm using QUO AOS, there is pretty much no ACPI to edit in the OC folder. So my guess is that there is some ACPI to edit in the bios. Could it be ?

 I've got this issue when trying to use the command: 
  #######################################################
 #                      USBMap                         #
#######################################################

Current Controllers:

 -        XHC1@14 @ _SB.PCI0.XHC1 (Needs Rename)
Traceback (most recent call last):
  File "./USBMap.py", line 1566, in <module>
    u.main()
  File "./USBMap.py", line 1488, in main
    if not "XHCI" in self.connected_controllers[x]["type"]: continue # Only check XHCI for RHUB paths
KeyError: 'XHC1@14000000'

I've got no clue of what to rename and where. Your help, if you can, would be really much appreciated. Thanks

**Comment by lionB777** [comment]
Solved, I found a way via a tool running under windows which is including this tool. it's named: USBToolbox. It's brainless. 
Thanks
